### ISSUE TITLE
`teco-core` isn’t being built

### ISSUE THREAD

**Issue by stevapple** [SwiftPackageIndex/SwiftPackageIndex-Server#2578]
**Which package(s) are showing incorrect data?**

- https://swiftpackageindex.com/teco-project/teco-core

**Please explain what data is incorrect and what you expected to see**

Build result doesn’t appear and the documentation is out of date.

**If the problem relates to the compatibility matrix, does it apply to specific builds?**

No. There’s no build shown.

**Comment by daveverwer** [comment]
Thanks for this @stevapple, and we are sorry the build results (and documentation) are not currently available. We had a serious issue this week which caused around half our build data to be deleted. That issue is being detailed in #2571.

We're currently re-processing builds as fast as we can, but with limited resources we won't be fully recovered for a few more days.

I will leave this ticket open until your builds recover, but there's not much more I can do at the moment. The builds are in the queue and will be processed automatically.

**Comment by daveverwer** [comment]
I just checked on this and it's all recovered now. Thanks very much for reporting the issue and our apologies again. This won't be a regular occurrence!

**Comment by stevapple** [comment]
It seems building result is still not correct? I’ve seen the `main` branch commit being correctly detected, but the build result is not shown and the documentation is outdated.

**Comment by daveverwer** [comment]
Hi @stevapple. Yes, it looks like the `main` branch is still in the build backlog, which our machines are still working through. However, the documentation does look to be correct to me.

Our logic on what documenttion to display follows this process:

* If there is a stable tagged release, display that
* If not, and there is a tagged pre-release (according to semantic versioning), display that
* If not, display the documentation on the default branch, if available.

So, even when your `main` branch builds, and the documentation along with it for that commit, the documentation link will still go to the latest tagged stable version.

We have ways around this, if that's not what you intend. I'd be happy to help with that. What would the ideal situation be for you? For it to go to `main` documentation from that link?

**Comment by stevapple** [comment]
I mean the documentation for "main" seems to be from the last commit? I guess there's room for improvement here, eg. the banner can be changed to "This documentation is from an older snapshot of the main branch" if we already know that the documentation build is outdated. And can we display the backlog state in build result, so users won't be confused?

**Comment by daveverwer** [comment]
> I guess there's room for improvement here

There is always room for improvement. We can only do our best.

> the banner can be changed to "This documentation is from an older snapshot of the main branch" if we already know that the documentation build is outdated. And can we display the backlog state in build result, so users won't be confused?

This is an unprecedented situation caused by a bug which had some serious side effects and has left the database in a state that our code does not expect to find it in. I am very sorry that the system had this bug, and we are doing our best to recover from it. We made a decision not to restore from a backup, as that had different side effects.

I can only, again, offer our sincere apologues for this problem.

**Comment by stevapple** [comment]
Okay I see. Didn’t realize that the incident hasn’t been fully addressed.🙏

**Comment by daveverwer** [comment]
> Okay I see. Didn’t realize that the incident hasn’t been fully addressed.🙏

We hope that the incident has been addressed in code now, however, we have thousands and thousands of builds still awaiting processing. We have limited resources to build every package with.

We hope the build backlog will be complete by early next week.

**Comment by stevapple** [comment]
Is the problem still impacting SPI? I observed build latency for hours after SPI has detected newer commit and release.

**Comment by finestructure** [comment]
It's not, however we've had capacity issues for a couple of weeks now. We're taking steps to improve the situation and should hopefully soon be back to faster processing. Thanks for your patience!
